/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.dcgov.parsedc;

import org.json.JSONException;
import org.json.JSONObject;

import android.os.Bundle;
import java.util.Set;
import org.appcelerator.kroll.KrollDict;


import android.content.BroadcastReceiver;
import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.util.Log;
import com.parse.ParsePushBroadcastReceiver;
import com.dcgov.parsedc.ParsedcModule;


public class ParsedcModuleBroadcastReceiver extends ParsePushBroadcastReceiver {
	private static final String TAG = "ParsedcModuleBroadcastReceiver";
	
	@Override
    public void onPushOpen(Context context, Intent intent) {
        Intent newIntent = context.getPackageManager().getLaunchIntentForPackage(context.getPackageName());
        newIntent.putExtras(intent.getExtras());
        context.startActivity(newIntent);
        String jsonData = newIntent.getExtras().getString("com.parse.Data");
        Log.d(TAG, "and data " + jsonData);
        //alert(jsonData);
        /*
        AlertDialog.Builder //alertDialogBuilder = new AlertDialog.Builder(
				context);
 
			// set title
			alertDialogBuilder.setTitle("DCOA");
 
			// set dialog message
			alertDialogBuilder.setMessage(jsonData);
				
 
				// create alert dialog
				AlertDialog alertDialog = alertDialogBuilder.create();
 
				// show it
				alertDialog.show();
        */
	} 
	
}
	